services:
  octopus:
    image: ghcr.io/mingtian886/octopus:latest
    pull_policy: always
    ports:
       - '8080:8080'
    volumes:      
       - '/vol1/1000/docker/zijiapi:/app/data'
    container_name: octopus
    restart: unless-stopped
